version: 2

fast_cache_dirs: &fast_cache_dirs
  paths:
    - "."
setup_docker: &setup_docker
  version: 17.10.0-ce
jobs:
  build:
    docker:
      - image: debian:stretch-slim
        environment:
          AWS_CLI_VERSION: 1.11.167
          AWS_DEFAULT_REGION: ap-southeast-2
          PYTHON_PIP_VERSION: 9.0.1
          NODE_ENV: development
    working_directory: ~/fast-dat-parser
    steps:
      - run: apt-get update
      - run: apt-get install -y wget git python-pip build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils clang cmake libogg-dev libvorbis-dev libflac-dev libfaad-dev libncursesw5-dev libasound2-dev libpulse-dev pulseaudio libmicrohttpd-dev libmp3lame-dev libcurl4-openssl-dev
      - run: apt-get install -y libleveldb-dev
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/fast-dat-parser
      - restore_cache:
          keys:
            - fast-{{ .Branch }}-cache-{{ arch }}
      # Install AWS CLI
      - run: pip install awscli==${AWS_CLI_VERSION}
      - run: make
      # - run: make install
      - run: ls -la ~/
      - run: aws s3 cp ~/parser s3://block.cointree.com/config/parser

      - save_cache:
         key: fast-{{ .Branch }}-cache-{{ arch }}
         <<: *fast_cache_dirs
      - persist_to_workspace:
         root: ~/fast-dat-parser
         <<: *fast_cache_dirs

workflows:
  version: 2
  api:
    jobs:
      - build
